### ISSUE TITLE
would be nice to have tags as objects

### ISSUE THREAD

**Issue by dmitry-saritasa** [calvinlough/ember-tag-input#1]
Right now 

![image](https://cloud.githubusercontent.com/assets/1747653/26076248/f744cd26-396c-11e7-9739-06d0fa2d2e4d.png)

```
{{tag-input
  tags=selectedItems
  property='title'
}}
```

would be nice to include property attr, that will look for that property inside 'selectedItems' array.

**Comment by calvinlough** [comment]
@dmitry-saritasa This is solved in the 1.0 release. See https://github.com/calvinlough/ember-tag-input/pull/4 for details. Basically now the tag input allows you to render each tag the way that you want.
