### ISSUE TITLE
how to handle addTag that returns a promise?

### ISSUE THREAD

**Issue by jabbermarky** [calvinlough/ember-tag-input#10]
I would like to save my new tag in my database. this save process returns a promise. What is the proper way to handle that in your addTag method?

**Comment by calvinlough** [comment]
To be honest I hadn't considered this use case. What you could do is immediately add it to the tags array and then remove it if the save fails. I would also draw it at 50% opacity or something until the save finishes. This should be possible since you're in control of rendering each tag.
