### ISSUE TITLE
Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by mcconkiee** [calvinlough/ember-tag-input#11]
hi - i'm getting the following error:
```
tag-input.js:53 Uncaught TypeError: Cannot read property 'indexOf' of undefined
    at Class.addNewTag (tag-input.js:53)
    at HTMLInputElement.<anonymous> (tag-input.js:92)
    at HTMLInputElement.dispatch (jquery.js:5206)
    at HTMLInputElement.elemData.handle (jquery.js:5014)
```
If i  set the `tags` array as `[]`, i receive this error as soon as i hit a seperator key (enter, space, etc). If i populate the `tags` array, the input looks great (blue bubbles with close) but same thing happens when i begin typing.

implemented like so, where `gear.sportList` is an empty array
```
{{#tag-input
	  tags=gear.sportList
	  addTag=(action 'addTag')
	  removeTagAtIndex=(action 'removeTagAtIndex')
	  as |tag|
	}}
	  {{tag}}
	{{/tag-input}}
```

my actions are implemented as in the example ... any advice?

**Comment by calvinlough** [comment]
Interesting. Can you try setting your tags array to Ember.A() instead of [] and let me know if you see the same error?

**Comment by travisdmathis** [comment]
@calvinlough i'm also running into this 

```
 if (!allowDuplicates && tags.indexOf(tag) >= 0) {
        return false;
 }
```

tag-input.js:53 Uncaught TypeError: Cannot read property 'indexOf' of undefined
    at Class.addNewTag (tag-input.js:53)
    at HTMLInputElement.<anonymous> (tag-input.js:92)
    at HTMLInputElement.dispatch (jquery.js:5206)
    at HTMLInputElement.elemData.handle (jquery.js:5014)

**Comment by calvinlough** [comment]
@travisdmathis I'm pretty stumped here. What browser & OS are you using?

**Comment by travisdmathis** [comment]
OSX, Chrome latest.

**Comment by mcconkiee** [comment]
@travisdmathis - i'm good now. Sooooo sorry... turns out `gear.sportList` in my application was indeed not being set. Solved by setting a `defaultValue` to `[]` in the model. Working now. FWIW - did not need `Ember.A`

**Comment by calvinlough** [comment]
I've added a guard in the v1.2.1 release that should handle this.
