### ISSUE TITLE
Published NPM Package is gigantic

### ISSUE THREAD

**Issue by bradleypriest** [calvinlough/ember-tag-input#117]
Hi there, was just doing a bundle size audit and it came up that the bundle size of this package is `>100MB`

<img width="606" alt="image" src="https://user-images.githubusercontent.com/167215/81487978-f1a31280-9295-11ea-92c6-5c825441da46.png">

<img width="169" alt="image" src="https://user-images.githubusercontent.com/167215/81487982-f7005d00-9295-11ea-877d-7f8cde49ee8c.png">

The 2.0.0 package seems to have been published with a full node_modules directory embedded.

Looks like this was a change between 1.2.2 and 2.0.0.

**Comment by calvinlough** [comment]
Whoops. Thanks for the report @bradleypriest! Fixed in 2.0.1 (https://github.com/calvinlough/ember-tag-input/releases/tag/v2.0.1)
