### ISSUE TITLE
How to get a notification if a user has entered duplicate value.

### ISSUE THREAD

**Issue by sonasingh46** [calvinlough/ember-tag-input#14]
How one can get notified if a user is entering the duplicate value?

**Comment by calvinlough** [comment]
There's no built in functionality for that, but you could easily do it yourself in your addTag handler. It gives you the tag it's trying to add so you can see if it's already in the array.

**Comment by sonasingh46** [comment]
Yes that is correct @calvinlough .... But what i  can see is that duplicate entry is already checked by the addon by default. 
So if in that process if any signal or etc is set to raise a alert for duplicate entry by the addon , that would provide flexibility for end users.
